- name: Install Apache
  apt: name=apache2 update_cache=yes state=latest

- name: Copy Index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
    backup: yes

- name: Start Apache
  service:
    name: apache2
    state: started
